# filebeat.yml
---
- hosts: grid
  user: root
  vars:
    filebeat: filebeat-5.5.0-x86_64.rpm

  tasks:

  - name: Create temp dir
    file: 
      path=/tmp/ansible 
      recurse=yes
      state=directory

  - name: Copy filebeat package to grid
    copy: 
      src: files/{{ filebeat }}
      dest: /tmp/ansible/{{ filebeat }}
      force: true

  - name: Install filebeat
    yum:
      name: /tmp/ansible/{{ filebeat }}
      state: present

  - name: Create patch variables
    set_fact:
      local_app_logs: "{{ path_app_logs | regex_replace(\"HOSTNAME\", ansible_hostname) }}"
      local_err_logs: "{{ path_err_logs | regex_replace(\"HOSTNAME\", ansible_hostname) }}"
      local_gc_logs: "{{ path_gc_logs | regex_replace(\"HOSTNAME\", ansible_hostname) }}"
      local_dstat_logs: "{{ path_dstat_logs | regex_replace(\"HOSTNAME\", ansible_hostname) }}"
      local_thread_dumps: "{{ path_thread_dumps | regex_replace(\"HOSTNAME\", ansible_hostname) }}"

  - name: Configure filebeat
    template:
      src=configs/filebeat/filebeat.yml.j2
      dest=/etc/filebeat/filebeat.yml

  - name: Restart filebeat
    service:
      name: filebeat
      state: restarted

  - name: Remove filebeat distrib
    file:
      path=/tmp/ansible/{{ filebeat }}
      state=absent