# filebeat.yml
---
- hosts: grid
  vars:
    filebeat: filebeat-5.5.0-x86_64.rpm
    server_app_logs: "{{ groups['server_app_logs'] }}"
    client_app_logs: "{{ groups['client_app_logs'] }}"
    server_err_logs: "{{ groups['server_err_logs'] }}"
    client_err_logs: "{{ groups['client_err_logs'] }}"
    server_gc_logs: "{{ groups['server_gc_logs'] }}"
    client_gc_logs: "{{ groups['client_gc_logs'] }}"
    server_thread_dumps: "{{ groups['server_thread_dumps'] }}"
    client_thread_dumps: "{{ groups['client_thread_dumps'] }}"

  tasks:

  - name: Create temp dir
    file: 
      path=/tmp/ansible 
      recurse=yes
      state=directory

  - name: Copy filebeat package to grid
    copy: 
      src: files/{{ filebeat }}
      dest: /tmp/ansible/{{ filebeat }}
      force: true

  - name: Install filebeat
    yum:
      name: /tmp/ansible/{{ filebeat }}
      state: present

  - name: Create patch variables
    set_fact:
      local_dstat_logs: "{{ common_dstat_logs | regex_replace(\"HOSTNAME\", ansible_hostname) }}"

  - name: Configure filebeat
    template:
      src=configs/filebeat/filebeat.yml.j2
      dest=/etc/filebeat/filebeat.yml

  - name: Restart filebeat
    service:
      name: filebeat
      state: restarted

  - name: Remove filebeat distrib
    file:
      path=/tmp/ansible/{{ filebeat }}
      state=absent
