# filebeat_config.yml
---
- hosts: grid
  vars:
    server_app_logs: "{{ groups['server_app_logs'] }}"
    client_app_logs: "{{ groups['client_app_logs'] }}"
    server_err_logs: "{{ groups['server_err_logs'] }}"
    client_err_logs: "{{ groups['client_err_logs'] }}"
    server_gc_logs: "{{ groups['server_gc_logs'] }}"
    client_gc_logs: "{{ groups['client_gc_logs'] }}"
    server_thread_dumps: "{{ groups['server_thread_dumps'] }}"
    client_thread_dumps: "{{ groups['client_thread_dumps'] }}"

  tasks:

  - name: Create patch variables
    set_fact:
      local_dstat_logs: "{{ common_dstat_logs | regex_replace(\"HOSTNAME\", ansible_hostname) }}"

  - name: Configure filebeat
    template:
      src=configs/filebeat/filebeat.yml.j2
      dest=/etc/filebeat/filebeat.yml

  - name: Restart filebeat
    service:
      name: filebeat
      state: restarted
