# kibana.yml
---
- hosts: elk

  tasks:

  - name: Configure kibana - create log dir
    file:
      path=/var/log/kibana
      state=directory
      owner=kibana

  - name: Configure kibana - kibana.yml
    template:
      src=configs/kibana/kibana.yml.j2
      dest=/etc/kibana/kibana.yml

  - name: Restart kibana
    service:
      name: kibana
      state: restarted

  - name: Import kibana dashboards
    debug:
      msg: "Manage->Objects->import file from playbook/config/kibana/export.json..."
